#!/bin/bash

# This bash script starts an existing verifastbuilder container

if ! podman image exists verifastbuilderimage ; then
  echo "no verifast builder image exists yet"
  echo ""
  echo "create one using the './scripts/create' command"
  echo ""
  exit 1
fi

if podman container exists verifastbuilder ; then
  podman container start verifastbuilder
else
  podman container run --interactive --tty \
    --security-opt label=disable \
    --device /dev/fuse \
    --volume $PWD:/common \
    --workdir /common \
    --name verifastbuilder \
    verifastbuilderimage \
    /bin/bash
fi
