#!/bin/bash

# This bash script uses deletes an existing container/image

if podman container exists verifastbuilder ; then
  podman container rm verifastbuilder
fi

if podman image exists verifastbuilderimage ; then
  podman image rm verifastbuilderimage
fi
