#!/bin/bash

# This bash script installs the specified version of opam

# see: https://api.github.com/repos/ocaml/opam/releases
#
OPAM_VERSION=2.1.2

case "$(uname -m)" in
  x86_64) OPAM_ARCH="x86_64" ;;
  i686) OPAM_ARCH="i686" ;;
  armv7l) OPAM_ARCH="armhf" ;;
  arm | arm64 | aarch64) OPAM_ARCH="arm64" ;;
  *) fail "Unsupported architecture" ;;
esac

echo OPAM VERSION: $OPAM_VERSION


cd /usr/local/bin

pwd

echo ""
echo "-----------------------------------------------------------------"
echo ""

wget -O opam https://github.com/ocaml/opam/releases/download/${OPAM_VERSION}/opam-${OPAM_VERSION}-${OPAM_ARCH}-linux

chmod a+x /usr/local/bin/opam

echo ""
echo "-----------------------------------------------------------------"
echo ""

opam init --disable-sandboxing \
  --dot-profile=/root/.bashrc --shell-setup \
  --yes

opam install ocamlfind ocamlbuild num camlp4 lablgtk z3 dune \
  csexp sexplib stdio cppo ocplib-endian stdint result capnp

# adwaita-icon-theme autoconf automake autopoint autotools-dev bsdmainutils
# build-essential dbus debhelper dh-autoreconf dh-strip-nondeterminism dirmngr
# dpkg-dev dwz fakeroot file fontconfig fontconfig-config fonts-dejavu-core
# gettext gettext-base gir1.2-atk-1.0 gir1.2-freedesktop gir1.2-gdkpixbuf-2.0
# gir1.2-glib-2.0 gir1.2-gtk-2.0 gir1.2-harfbuzz-0.0 gir1.2-pango-1.0 gnupg
# gnupg-l10n gnupg-utils gpg gpg-agent gpg-wks-client gpg-wks-server gpgconf
# gpgsm gpgv groff-base gtk-update-icon-cache hicolor-icon-theme
# humanity-icon-theme icu-devtools intltool-debian libalgorithm-diff-perl
# libalgorithm-diff-xs-perl libalgorithm-merge-perl libapparmor1
# libarchive-cpio-perl libarchive-zip-perl libassuan0 libatk1.0-0
# libatk1.0-data libatk1.0-dev libavahi-client3 libavahi-common-data
# libavahi-common3 libblkid-dev libbsd0 libcairo-gobject2
# libcairo-script-interpreter2 libcairo2 libcairo2-dev libcroco3 libcups2
# libdatrie-dev libdatrie1 libdbus-1-3 libdebhelper-perl libdpkg-perl libelf1
# libfakeroot libffi-dev libfile-fcntllock-perl
# libfile-stripnondeterminism-perl libfontconfig1 libfontconfig1-dev
# libfreetype-dev libfreetype6 libfreetype6-dev libfribidi-dev libfribidi0
# libgail-common libgail18 libgdk-pixbuf2.0-0 libgdk-pixbuf2.0-bin
# libgdk-pixbuf2.0-common libgdk-pixbuf2.0-dev libgirepository-1.0-1
# libglib2.0-0 libglib2.0-bin libglib2.0-data libglib2.0-dev
# libglib2.0-dev-bin libgmpxx4ldbl libgraphite2-3 libgraphite2-dev libgtk2.0-0
# libgtk2.0-bin libgtk2.0-common libharfbuzz-dev libharfbuzz-gobject0
# libharfbuzz-icu0 libharfbuzz0b libice-dev libice6 libicu-dev libicu66
# libjbig0 libjpeg-turbo8 libjpeg8 libksba8 liblocale-gettext-perl libltdl-dev
# libltdl7 liblzo2-2 libmagic-mgc libmagic1 libmail-sendmail-perl libmount-dev
# libmpdec2 libnpth0 libpango-1.0-0 libpango1.0-dev libpangocairo-1.0-0
# libpangoft2-1.0-0 libpangoxft-1.0-0 libpcre16-3 libpcre2-16-0 libpcre2-32-0
# libpcre2-dev libpcre2-posix2 libpcre3-dev libpcre32-3 libpcrecpp0v5
# libpipeline1 libpixman-1-0 libpixman-1-dev libpng-dev libpng-tools
# libpng16-16 libpthread-stubs0-dev libpython3-stdlib libpython3.8-minimal
# libpython3.8-stdlib librsvg2-2 librsvg2-common libselinux1-dev libsepol1-dev
# libsigsegv2 libsm-dev libsm6 libsub-override-perl libsys-hostname-long-perl
# libthai-data libthai-dev libthai0 libtiff5 libtool libuchardet0 libwebp6
# libx11-6 libx11-data libx11-dev libxau-dev libxau6 libxcb-render0
# libxcb-render0-dev libxcb-shm0 libxcb-shm0-dev libxcb1 libxcb1-dev
# libxcomposite-dev libxcomposite1 libxcursor-dev libxcursor1 libxdamage-dev
# libxdamage1 libxdmcp-dev libxdmcp6 libxext-dev libxext6 libxfixes-dev
# libxfixes3 libxft-dev libxft2 libxi-dev libxi6 libxinerama-dev libxinerama1
# libxml2 libxml2-utils libxrandr-dev libxrandr2 libxrender-dev libxrender1 m4
# man-db pango1.0-tools pinentry-curses po-debconf python3-lib2to3
# python3-minimal python3.8 python3.8-minimal shared-mime-info tzdata
# ubuntu-mono uuid-dev x11-common x11proto-core-dev x11proto-dev
# x11proto-input-dev x11proto-randr-dev x11proto-xext-dev
# x11proto-xinerama-dev xdg-user-dirs xorg-sgml-doctools xtrans-dev xz-utils
# zlib1g-dev
