#!/bin/bash

# This bash script automates the build of the vfdeps dependencies

git clone --depth 1 https://github.com/verifast/vfdeps.git

cd vfdeps

patch --strip=1 < ../buildScripts/vfdeps-build.sh.patch

./setup-build.sh

./build.sh

