#!/bin/bash

# This bash script automates the build of the vfdeps dependencies

if [[ ! -d vfdeps ]] ; then
  git clone --depth 1 https://github.com/verifast/vfdeps.git
fi

cd vfdeps

#./setup-build.sh
#
echo "tzdata tzdata/Areas select Europe" > preSeed.txt
echo "tzdata tzdata/Zones/Europe select London" >> preSeed.txt
debconf-set-selections preSeed.txt
rm -rf /etc/timezone
rm -rf /etc/localtime

apt-get update
apt-get install -y --no-install-recommends \
  git wget ca-certificates make m4 \
  gcc g++ patch unzip libgtk2.0-dev \
  valac libgtksourceview2.0-dev

# ./build.sh
#
#make PREFIX=/usr/local JOBS=$(nproc) --jobs=$(nproc)

