#!/bin/bash

# This bash script automates the build of the vfdeps dependencies

if [[ ! -d vfdeps ]] ; then
  git clone --depth 1 https://github.com/verifast/vfdeps.git
fi

cd vfdeps

if test -z "$(grep OCAMLBUILD_BINARY Makefile | grep  CPPO_BINARY)" ; then
  echo patch --strip=1 < ../buildScripts/vfdeps-Makefile.patch
fi

#./setup-build.sh
#
echo "tzdata tzdata/Areas select Europe" > preSeed.txt
echo "tzdata tzdata/Zones/Europe select London" >> preSeed.txt
debconf-set-selections preSeed.txt
rm -rf /etc/timezone
rm -rf /etc/localtime

apt-get update
apt-get install -y --no-install-recommends \
  git wget ca-certificates make m4 \
  gcc g++ patch unzip libgtk2.0-dev \
  valac libgtksourceview2.0-dev



# ./build.sh
#
make PREFIX=/usr/local JOBS=$(nproc) --jobs=$(nproc)

if ! $? ; then
  echo make result: 1

  # for some reason... we need to do this twice ;-(
  #
  make PREFIX=/usr/local JOBS=$(nproc) --jobs=$(nproc)

  echo make result: $?
fi